config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users do
        collection do
            get :login_form
            post :login, as: :login
        end
    end

    namespace :rest do 
        post 'login', to: 'webservice1#login', as: :login
        post 'verify_user/:email', to: 'webservice2#verify_user', as: :verify_user, constraints: { email: /[a-zA-Z0-9_\.+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+/}
    end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :null_session
end

app/controllers/rest/webservice1_controller.rb
class Rest::Webservice1Controller < ApplicationController
	include Webservice

	def login
		if Rails.env.production?
		    uri = "http://restror.herokuapp.com/rest/verify_user/" + params[:email]
		else
		    uri = "http://localhost:3000/rest/verify_user/" + params[:email]
		end
		
		body = {
		  "image" => params[:image]
		}

		response = request_to_uri(uri, body)

		render json: JSON.parse(response.body), status: response.code
	end

	private

	def user_params
		params.require(:user).permit(:email, :image)
	end
end

app/controllers/rest/webservice2_controller.rb
class Rest::Webservice2Controller < ApplicationController
	def verify_user
		user = User.where(email: params[:email]).first
		
		if user.nil?
			message, status = { "message" => "No encontrado" }, 404 
		else 
			# If images are equals, simulate a 10% error
			if user.image == params[:image] and rand(0..100) > 10
				message, status = { "message" => "OK" }, 200
			else
				message, status = { "message" => "No autorizado" }, 401
			end
		end

		render json: message, status: status
	end

	private

	def user_params
		params.require(:user).permit(:email, :image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    require 'base64'

    include Webservice

    # GET /users
    # returns all users
    def index
    	@users = User.all
    end

    # GET /users/:id
    # returns a specific user
    def show
    	@user = User.find(params[:id])
    end

    # GET /users/new
    # return an empty user
    def new
        @user = User.new
    end

    # POST /users
    # creates a user
    def create
        @user = User.new

        @user.email = params[:user][:email]
        @user.image = Base64.encode64(File.read(params[:user][:image].path))

        if @user.save
            flash[:success] = "Usuario creado correctamente"
            redirect_to @user
        else
            flash[:error] = "No se pudo crear el usuario"
            redirect_to new_user_path
        end
    end

    # GET /users/login
    def login_form
        puts request.host
    end

    # POST /users/login
    def login
        if Rails.env.production?
            uri = "http://restror.herokuapp.com/rest/login"
        else
            uri = "http://localhost:3000/rest/login"
        end
        
        body = {
          "email" => params[:email],
          "image" => Base64.encode64(File.read(params[:image].path))
        }

        response = request_to_uri(uri, body)

        if response.code == "200"
            flash[:success] = "Usuario verificado"
        else
            flash[:error] = "No se pudo verificar el usuario"
        end

        user = User.where(email: params[:email]).first
        UserNotifierMailer.send_login_notification(user, response.code, request.user_agent).deliver

        redirect_to login_form_users_path
    end


    # GET /users/:id/edit
    # returns a specific user
    def edit
        @user = User.find(params[:id])
    end

    # PATCH /users/:id
    # PUT /users/:id
    # updates a user
    def update
        @user = User.find(params[:id])
        @user.image = Base64.encode64(File.read(params[:user][:image].path))
        if @user.save
            flash[:success] = "Usuario actualizado correctamente"
        else
            flash[:error] = "No se pudo actualizar el usuario"
        end
        redirect_to @user
    end

    # DELETE /users/:id
    # deletes a user
    def destroy
        @user = User.find(params[:id])
        if @user.destroy
            flash[:success] = "Usuario eliminado correctamente"
        else
            flash[:error] = "Usuario no pudo ser eliminado"
        end

        redirect_to users_path
    end

    private

    def user_params
    	params.require(:user).permit(:email, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rest/webservice1_helper.rb
module Rest::Webservice1Helper
end

app/helpers/rest/webservice2_helper.rb
module Rest::Webservice2Helper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restror</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_flash.html.erb
<% flash.each do |key, value| %>
  <p><%= content_tag :div, value, class: "flash #{key}" %></p>
<% end %>

app/views/users/_user_form.html.erb
<%= render 'flash' %>

<%= form_for @user do |f| %>
    
    
    <% if new_user %>
        <p><%= f.label :email, "Email" %></p>
        <p><%= f.email_field :email %></p>
    <% else %>
        <p>Email: <%= @user.email %></p>
    <% end %>
    
    <p><%= f.label :image, "Imagen" %></p>

    <% if @user.image.present? %>
        <p>Imagen actual:</p>
        <p><%= image_tag "data:image/jpeg;base64,#{@user.image}", class: 'resize' %></p>
    <% end %>
    
    <p><%= f.file_field :image %></p>

    <%= f.submit "Enviar" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editar</h1>

<%= render 'user_form', new_user: false %>

<p><%= link_to "Index", users_path %></p>

app/views/users/index.html.erb
<h1>Usuarios</h1>

<%= render 'flash' %>

<p><%= link_to "Nuevo usuario", new_user_path %></p>
<p><%= link_to 'Login', login_form_users_path %></p>

<table>
    <tr>
        <td>Email</td>
        <td>Imagen</td>
        <td>Acciones</td>
    </tr>
    <% @users.each do |u| %>
        <tr>
            <td><%= u.email %></td> 
            <td><%= image_tag "data:image/jpeg;base64,#{u.image}", class: "resize" %></td>
            <td><%= link_to "Editar", edit_user_path(u) %>, <%= link_to "Eliminar", { action: :destroy, id: u.id }, method: :delete, data: { confirm: '¿Estás Seguro?' } %></td>
        </tr>
    <% end %>
</table>

app/views/users/login_form.html.erb
<h1>Login</h1>

<%= form_tag login_users_path, method: :post, multipart: true do %>
    <p>Email</p>
    <%= email_field_tag "email", nil, required: true %>

    <p>Imagen</p>
    <%= file_field_tag "image", required: true %>

    <%= submit_tag "Enviar" %>
<% end %>

<%= render 'flash' %>
<p><%= link_to "Index", users_path %></p>

app/views/users/new.html.erb
<h1>Nuevo</h1>

<%= render 'user_form', new_user: true %>

<p><%= link_to "Index", users_path %></p>

app/views/users/show.html.erb
<h1>Usuario</h1>

<%= render 'flash' %>

<p><%= @user.email %></p>
<p><%= image_tag "data:image/jpeg;base64,#{@user.image}", class: "resize" %> </p>

<p><%= link_to "Editar", edit_user_path(@user) %></p>
<p><%= link_to "Index", users_path %></p>